-- Оновлена міграція для логування за логіном
DROP TABLE IF EXISTS public.audit_logs;

CREATE TABLE public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_login TEXT NOT NULL, -- Логін або ПІБ користувача
    user_role TEXT,          -- Роль (Адмін, Слюсар і т.д.)
    action TEXT NOT NULL,    -- Тип дії
    act_id BIGINT,
    details JSONB DEFAULT '{}'::jsonb
);

-- Дозволяємо вставку всім (оскільки авторизація кастомна)
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow insert for all" ON public.audit_logs
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow select for authenticated users" ON public.audit_logs
    FOR SELECT USING (auth.role() = 'authenticated');
